### ISSUE TITLE
Updated 7zSFX modified module

### ISSUE THREAD

**Issue by sharkykh** [git-for-windows/7-Zip#1]
Hey @dscho,
This is related to git-for-windows/git#1131,
I just wanted to share this repo with you: https://github.com/chrislake/7zsfxmm

I can't really tell from the code, but from the commits it seems like that repo took the original code of the modified 7zSFX module (the one by Oleg Scherbakov) and updated it to work with the latest 7-zip code.
It's brand new, but I thought you might want to take a quick look at it!

**Comment by dscho** [comment]
Thanks for the pointer.

One of the original reasons to switch away from the modified 7-Zip SFX was to avoid security concerns in that module's source code (just some API calls that were considered no longer safe).

Another reason was to lighten the maintenance burden by leaving the responsibility to another project, i.e. 7-Zip's.

Ideally, the patches would eventually get into 7-Zip's code itself, of course, but there are few enough that it would not matter all that much.

If the repository indicated by you turns out to address both concerns, we can easily reconsider which SFX module to use in portable Git.

**Comment by dscho** [comment]
For the record, my Visual Studio 2015 and also my Visual Studio 2017 fail to build that code... Maybe you have more luck?

**Comment by sharkykh** [comment]
Unfortunately, I don't know or code in C / C++, so I don't actually have VS to try this...
[Maybe 2010 is needed?](https://github.com/chrislake/7zsfxmm/commit/51139022f6d790da60884077b63b2f265052be0b) I really don't know how this works.

**Comment by dscho** [comment]
> Maybe 2010 is needed?

Probably. Let's wait and see. (I have no time to get it to work with VS 2015 right now.)

**Comment by sharkykh** [comment]
> Maybe 2010 is needed?

https://github.com/chrislake/7zsfxmm/releases/tag/1.7.0.3900
Looks like that is the case, for the time being.

**Comment by sharkykh** [comment]
I do not need this anymore.
(Decided to use `7za.exe x "MinGit-<version>-<arch>.zip" -o"C:\Git"`)
